comment on table public. accountreg  is   ' Сметкоплан';
comment on table public. act  is   ' Акт';
comment on table public. action  is   ' Мерки';
comment on table public. address  is   ' Адреси';
comment on table public. admregion  is   ' Административен район';
comment on table public. agent  is   ' Тип посредник';
comment on table public. baccount  is   ' Банкови сметки на общината';
comment on table public. baldebtinst  is   ' Дължими вноски';
comment on table public. baloverinst  is   ' Надвнесени суми';
comment on table public. building  is   ' Сграда';
comment on table public. carreg  is   ' Регистър на марки и модели автомобили /NomKoli/';
comment on table public. cartaxprice  is   ' Цени на данък превозни средства';
comment on table public. city  is   ' Населено место';
comment on table public. company  is   ' Посредник';
comment on table public. delegatecompany  is   ' Права за работа с общини';
comment on table public. containernorm  is   ' Годишни суми за сметосъбиране по видови съдове';
comment on table public. country  is   ' Държава';
comment on table public. debtinstalment  is   ' Дължими вноски';
comment on table public. debtinstalmentcorr  is   ' Корекции на дължими вноски';
comment on table public. debtpartproperty  is   ' Разпределение на собствеността';
comment on table public. debtsubject  is   ' Задължения на данъчен субект';
comment on table public. debtsubjectcorr  is   ' Корекции на задължение на дан. субект по декларация';
comment on table public. decode  is   ' Номенклатури';
comment on table public. department  is   ' Отдел';
comment on table public. directdebit  is   ' Незабавно инкасо';
comment on table public. discount  is   ' Отстъпки';
comment on table public. documenttype  is   ' Типове документи/декларации';
comment on table public. dog  is   ' Декларация по чл.117 за притежавано куче';
comment on table public. exchange_reg  is   ' Видове валута и ценни книжа';
comment on table public. finishcashier  is   ' Ежедневно приключване на касиер';
comment on table public. finishday  is   ' Ежедневно приключване';
comment on table public. firmproperty  is   ' Даньк върху недвижимите имоти';
comment on table public. firmpropobj  is   ' Недвижими имоти/обекти/Сгради - чл.17';
comment on table public. fromaddressorg  is   ' Адреси на нефизически лица';
comment on table public. fromcharsubject  is   ' Характеристики на субекта';
comment on table public. fromkat  is   ' Информация за превозни средства от КАТ/PRMKAT/';
comment on table public. garbproperty  is   ' ТБО за имот';
comment on table public. garbtax  is   ' Такса битови отпадъци по чл.19 и 71';
comment on table public. getproperty  is   ' Декларация по чл.49 за придобиване на имущества';--comment on table public. groupagent  is   ' Група посредници напр - събирачи(?) Поща Интернет Салони на общината - гишета';
comment on table public. grouptbo  is   ' Групи ТБО';
comment on table public. homeobj  is   ' Обекти за имоти на граждани и жилища на юредически лица';
comment on table public. inheritance  is   ' Декларация по чл.32 за данък върху наследството';
comment on table public. interestdebt  is   ' Начислени лихви по задължения';
comment on table public. interestoper  is   ' Операции по начисление/сторно на лихва';
comment on table public. interestpct  is   ' Лихвен процент';
comment on table public. invoice  is   ' Фактура';
comment on table public. kinddebtreg  is   ' Списък на кодове на вид задължение /плащане/ и ТБО, пътен данък.... и Безобложни приходи?';
comment on table public. kindhomeobjreg  is   ' Регисър - вид на обекта /NVIDOB/';
comment on table public. kindparreg  is   ' Вид подпараграф';
comment on table public. land  is   ' Земя';
comment on table public. message  is   ' Съобщения - декларации';
comment on table public. municipality  is   ' Община';
comment on table public. normbs  is   ' Нормативна базисна стойност на земя и сгради';
comment on table public. operation  is   ' Служебни операции';
comment on table public. operdebt  is   ' операции по задължения- вноски';
comment on table public. oversubject  is   ' Надвнесени суми по клиенти';
comment on table public. partgetproperty  is   ' Собственици на придобито имущество';
comment on table public. parthomeobj  is   ' Разпределение на частите на собствеността';
comment on table public. partinheritance  is   ' Наследници/ Заветници';
comment on table public. partland  is   ' Право на собств/ползване върху земята';
comment on table public. partproperty  is   ' Собственици/ползватели на имот';
comment on table public. parttransport  is   ' Собственици на превозни средства';
comment on table public. patent  is   ' Данъчна декларация за облагане с патентен данък';
comment on table public. patentactivity  is   ' Патентни дейности';
comment on table public. patentactivityobj  is   ' Патентни дейности - обекти';
comment on table public. patentactivityreg  is   ' Регистър на услуги, подлежащи на патентното облагане';
comment on table public. patentother  is   ' Дейност, извършвана с личен труд на територията на друга община';
comment on table public. patenttaxprice  is   ' Цени на патентни дейности';
comment on table public. patentzone  is   ' Зони за патентен данък';
comment on table public. paydebt  is   ' Платени задължения';
comment on table public. paydocument  is   ' Платежни документи';
comment on table public. paytransaction  is   ' Операции';
comment on table public. promtbo  is   ' Промил';
comment on table public. property  is   ' Имот / Imop /';
comment on table public. province  is   ' Област';
comment on table public. rdvr  is   ' Районна дирекция на Вътрешните работи (РДВР)';
comment on table public. regnumber  is   ' Деловоден номер';
comment on table public. relief  is   ' Облекчение за ФЛ';
comment on table public. representative  is   ' Представител';
comment on table public. request  is   ' Молби, искания, заявления';
comment on table public. resolution  is   ' Решения';
comment on table public. rpureg  is   ' Номенклатура РПУ /OBLKAT/';
comment on table public. servgroup  is   ' Групи на услуги по общините';
comment on table public. servicereg  is   ' Класификатор на услуги';
comment on table public. street  is   ' Улица';
comment on table public. tabinheritance  is   ' Имущества и задължения /Таблици/';
comment on table public. tabinhreg  is   ' Описание на таблици за наследствата';
comment on table public. taxdoc  is   ' Входящи документи /декларации..../ Още при създаване пишем XML структура - оригинал в архива';
comment on table public. taxobject  is   ' Данъчен обект / имот,МПС/';
comment on table public. taxperiod  is   ' Данъчен период';
comment on table public. taxperiodpay  is   ' Срокове за плащане на задължения по типове документи';
comment on table public. taxsubject  is   ' Данъчен субект';
comment on table public. transpmeansreg  is   ' Регистър на транспортни средства';
comment on table public. transport  is   ' Дакларация за превозни, плавателни и въздухоплавателни средства разбивката от TransMeansReg /prm541, prm542, prmbez/';
comment on table public. trucktaxprice  is   ' Цени на данък за товарни автомобили и влекачи';
comment on table public. tvbuilding  is   ' Сграда за ДО';
comment on table public. tvhomeobj  is   ' Обекти за имоти на граждани и жилища на юредически лица за ДО';
comment on table public. tvland  is   ' Земя за ДО';
comment on table public. tvparthomeobj  is   ' Разпределение на частите на собствеността';
comment on table public. tvpartland  is   ' Право на собств/ползване върху земята';
comment on table public. tvpartproperty  is   ' Собственици/ползватели на имот';
comment on table public. tvproperty  is   ' Имот - За Удостоверения за ДО';
comment on table public. tvtaxdoc  is   ' Документ за издаване на ДО';
comment on table public. workhistory  is   ' История на обработка на декларации  и искания';